@php
    // The product in the order a person meets it. Every figure is a real capture
    // of this app (public/landing, regenerated by nexo-shots.mjs from a local
    // instance seeded with DemoSeeder) — never a redrawn screen.
    $steps = [
        ['shot' => 'shot-1', 'caption' => __('1 — Add your links')],
        ['shot' => 'shot-2', 'caption' => __('2 — Share your page')],
        ['shot' => 'shot-3', 'caption' => __('3 — Read your numbers, cookie-free')],
    ];

    // Every row is something the code enforces, and the source is named next to
    // it. A row with no real source does not exist (design.md, "Copy").
    $specs = [
        // RegisteredUserController::store (min:3, max:30) + App\Rules\Username::FORMAT;
        // the reserved list is read at runtime so the count cannot drift from config.
        [__('Public username'), __('3–30 characters; lowercase, digits, - and _; :count reserved', [
            'count' => count((array) config('nexo.reserved_usernames')),
        ])],
        // StoreLinkRequest::rules (max:120 / max:2048) + App\Rules\LinkUrl::ALLOWED_SCHEMES.
        [__('Link title and URL'), __('Title up to 120 · URL up to 2048, http/https/mailto/tel')],
        // App\Support\VisitorHash::make — app key + date + IP + user agent, none stored.
        [__('Visitor metric'), __('Daily-rotating SHA-256 hash — no IP or cookie stored')],
        // AnalyticsController::RANGES.
        [__('Analytics ranges'), __('7 · 30 · 90 days')],
        // StoreLinkRequest::rules (starts_at / ends_at) + App\Models\Link::isUpcoming.
        [__('Link scheduling'), __('Optional start and end, countdown computed on the fly')],
        // config/nexo.php → locales, plus the shared theme toggle.
        [__('Languages and themes'), __('es · en · pt — light and dark')],
    ];

    // The same answers the help center gives, in the same words — the landing
    // does not get a marketing rewrite of them.
    $faqs = array_slice((array) __('help.faqs'), 0, 4);
@endphp

<x-landing-layout :title="__('Share all your links in one place.')"
                  :description="__('An open-source link-in-bio page you host yourself — with visitor analytics that don\'t spy on anyone.')">

    <section data-landing-section="hero">
        <div class="mx-auto max-w-4xl px-6">
            <h1 class="max-w-2xl text-4xl font-semibold tracking-tight text-ink sm:text-5xl">{{ __('Share all your links in one place.') }}</h1>
            <p class="mt-5 max-w-xl text-lg text-muted">{{ __('An open-source link-in-bio page you host yourself — with visitor analytics that don\'t spy on anyone.') }}</p>
            <div class="mt-8 flex flex-wrap gap-3">
                <a class="nexo-btn nexo-btn--primary" href="{{ route('register') }}">{{ __('Create your page') }}</a>
                <a class="nexo-btn nexo-btn--ghost" href="{{ route('login') }}">{{ __('Sign in') }}</a>
            </div>
        </div>
    </section>

    <section data-landing-section="producto">
        <div class="mx-auto max-w-4xl px-6">
            <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('How it works') }}</h2>

            {{-- Kept from the landing this replaces: before any screenshot, the
                 shape of a page from THIS instance, and the way into the live
                 one. The link only renders when the example page exists — its
                 tests cover both branches. --}}
            <div class="mt-6 rounded-2xl border border-line bg-surface p-5 sm:p-6">
                <p class="break-all text-xl font-semibold tracking-tight text-ink sm:text-2xl">
                    {{ preg_replace('#^https?://#', '', url('/')) }}/<span class="text-primary">{{ config('nexo.example_username') }}</span>
                </p>
                @if ($exampleUsername !== null)
                    <p class="mt-3">
                        <a href="{{ url('/'.$exampleUsername) }}" class="inline-flex min-h-11 items-center text-sm font-medium text-link hover:text-link-hover hover:underline">{{ __('See a live example') }}</a>
                    </p>
                @endif
            </div>

            <div class="mt-10 space-y-10 sm:mt-12 sm:space-y-12">
                @foreach ($steps as $step)
                    <figure>
                        {{-- Four files per figure: theme × viewport. Both themes
                             ship because landing.css shows the one that matches
                             [data-theme]; both viewports ship because a 1280×800
                             capture shrunk to a phone is not the "legible without
                             zoom" STANDARD.md asks for. width/height are the real
                             pixels of each file, so nothing reflows on load. --}}
                        <img class="landing-shot landing-shot--desktop landing-shot--light w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-light.webp"
                             width="1280" height="800" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <img class="landing-shot landing-shot--desktop landing-shot--dark w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-dark.webp"
                             width="1280" height="800" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <img class="landing-shot landing-shot--mobile landing-shot--light w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-mobile-light.webp"
                             width="390" height="844" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <img class="landing-shot landing-shot--mobile landing-shot--dark w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-mobile-dark.webp"
                             width="390" height="844" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <figcaption class="mt-3 text-sm text-muted">{{ $step['caption'] }}</figcaption>
                    </figure>
                @endforeach
            </div>

            <p class="mt-8 text-sm text-muted">
                <a href="{{ config('nexo.repository_url') }}" rel="noopener" class="inline-flex min-h-11 items-center font-medium text-link hover:text-link-hover hover:underline">{{ __('Open source on GitHub') }}</a>
            </p>
        </div>
    </section>

    <section data-landing-section="datos">
        <div class="mx-auto max-w-4xl px-6">
            <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('The numbers') }}</h2>
            <dl class="mt-6 border-t border-line">
                @foreach ($specs as [$term, $value])
                    <div class="flex flex-col gap-1 border-b border-line py-3 sm:flex-row sm:gap-6 sm:py-4">
                        <dt class="text-sm font-medium text-ink sm:w-56 sm:shrink-0">{{ $term }}</dt>
                        <dd class="text-sm tabular-nums text-muted">{{ $value }}</dd>
                    </div>
                @endforeach
            </dl>
        </div>
    </section>

    <section data-landing-section="preguntas">
        <div class="mx-auto max-w-4xl px-6">
            <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('Frequent questions') }}</h2>
            <div class="mt-6 border-t border-line">
                @foreach ($faqs as $faq)
                    <details class="border-b border-line">
                        <summary class="flex min-h-11 cursor-pointer items-center text-sm font-medium text-ink">{{ $faq['q'] ?? '' }}</summary>
                        <div class="pb-4 text-sm text-muted">{!! $faq['a'] ?? '' !!}</div>
                    </details>
                @endforeach
            </div>
            <p class="mt-4">
                {{-- inline-flex + min-h-11: a thumb needs 44px, and an inline
                     link is 18 (STANDARD.md, mobile-first). --}}
                <a href="{{ route('help') }}" class="inline-flex min-h-11 items-center text-sm font-medium text-link hover:text-link-hover hover:underline">{{ __('All questions') }}</a>
            </p>
        </div>
    </section>

    <section data-landing-section="cierre">
        <div class="mx-auto max-w-4xl px-6">
            <a class="nexo-btn nexo-btn--primary" href="{{ route('register') }}">{{ __('Create your page') }}</a>
        </div>
    </section>
</x-landing-layout>
